spring:
  application:
    name: bakery-management-system
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.abilnsbdswpgpwneuynb
    password: Dat04022005@@1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true